const reportData = [
  {
    id: 1,
    customerName: "Nguyễn Văn A",
    phone: "090 123 4567",
    propertyTitle: "Nhà phố thương mại 2 mặt tiền",
    propertyPrice: "8.9 Tỷ",
    propertyImage: "images/house_3.png",
    date: "2025-12-10",
    time: "09:30",
    status: "pending",
  },
  {
    id: 2,
    customerName: "Trần Thị B",
    phone: "091 888 9999",
    propertyTitle: "Nhà cấp 4 mái Thái sân vườn",
    propertyPrice: "2.5 Tỷ",
    propertyImage: "images/house_level_4.png",
    date: "2025-12-09",
    time: "14:15",
    status: "confirmed",
  },
  {
    id: 3,
    customerName: "Lê Văn C",
    phone: "098 765 4321",
    propertyTitle: "Căn hộ Penthouse view sông",
    propertyPrice: "12.5 Tỷ",
    propertyImage: "images/apartment_view.png",
    date: "2025-12-08",
    time: "10:00",
    status: "cancelled",
  },
  {
    id: 4,
    customerName: "Phạm Minh D",
    phone: "093 333 4444",
    propertyTitle: "Nhà phố 3 tầng hiện đại",
    propertyPrice: "5.2 Tỷ",
    propertyImage: "images/house_townhouse.png",
    date: "2025-12-08",
    time: "08:45",
    status: "confirmed",
  },
  {
    id: 5,
    customerName: "Hoàng Thị E",
    phone: "090 555 6666",
    propertyTitle: "Biệt thự sân vườn hiện đại",
    propertyPrice: "15.5 Tỷ",
    propertyImage: "images/villa_interior.png",
    date: "2025-12-07",
    time: "16:20",
    status: "confirmed",
  },
  {
    id: 6,
    customerName: "Đỗ Văn F",
    phone: "097 777 8888",
    propertyTitle: "Căn hộ cao cấp view biển",
    propertyPrice: "4.2 Tỷ",
    propertyImage: "images/hero_bg.png",
    date: "2025-12-06",
    time: "09:00",
    status: "pending",
  },
  {
    id: 7,
    customerName: "Ngô Thị G",
    phone: "096 111 2222",
    propertyTitle: "Nhà phố thương mại 2 mặt tiền",
    propertyPrice: "8.9 Tỷ",
    propertyImage: "images/house_3.png",
    date: "2025-12-06",
    time: "11:30",
    status: "confirmed",
  },
  {
    id: 8,
    customerName: "Bùi Văn H",
    phone: "094 444 5555",
    propertyTitle: "Biệt thự Mini Tân Cổ Điển",
    propertyPrice: "7.8 Tỷ",
    propertyImage: "images/house_2.png", // Assuming image exists or reuse
    date: "2025-12-05",
    time: "15:45",
    status: "confirmed",
  },
  {
    id: 9,
    customerName: "Vũ Thị I",
    phone: "093 999 0000",
    propertyTitle: "Nhà cấp 4 mái Thái sân vườn",
    propertyPrice: "2.5 Tỷ",
    propertyImage: "images/house_level_4.png",
    date: "2025-12-05",
    time: "08:15",
    status: "cancelled",
  },
  {
    id: 10,
    customerName: "Dương Văn K",
    phone: "091 222 3333",
    propertyTitle: "Nhà phố 3 tầng hiện đại",
    propertyPrice: "5.2 Tỷ",
    propertyImage: "images/house_townhouse.png",
    date: "2025-12-04",
    time: "13:00",
    status: "confirmed",
  },
];
